"""Update Restaurant model for Google Places API

Revision ID: 923155cef0d2
Revises: 
Create Date: 2025-09-15 03:43:25.586677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923155cef0d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('role')
    op.drop_table('guest_user')
    op.drop_table('vote')
    op.drop_table('restaurant')
    op.drop_table('roles_users')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('fs_webauthn_user_handle', sa.VARCHAR(length=64), nullable=True),
    sa.Column('mf_recovery_codes', sa.TEXT(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('us_phone_number', sa.VARCHAR(length=128), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('us_totp_secrets', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('fs_uniquifier', sa.VARCHAR(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.Column('current_login_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login_ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('current_login_ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('login_count', sa.INTEGER(), nullable=True),
    sa.Column('tf_primary_method', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tf_totp_secret', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tf_phone_number', sa.VARCHAR(length=128), nullable=True),
    sa.Column('create_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier'),
    sa.UniqueConstraint('fs_webauthn_user_handle'),
    sa.UniqueConstraint('us_phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('restaurant',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('RoomID', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('categories', sa.TEXT(), nullable=True),
    sa.Column('price', sa.VARCHAR(length=10), nullable=True),
    sa.Column('review_count', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['RoomID'], ['room.RoomID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('VoteID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('GuestUserID', sa.INTEGER(), nullable=False),
    sa.Column('RoomID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('RestaurantID', sa.VARCHAR(length=50), nullable=False),
    sa.Column('VoteChoice', sa.INTEGER(), nullable=False),
    sa.Column('VoteTime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['GuestUserID'], ['guest_user.id'], ),
    sa.ForeignKeyConstraint(['RestaurantID'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['RoomID'], ['room.RoomID'], ),
    sa.PrimaryKeyConstraint('VoteID')
    )
    op.create_table('guest_user',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('Username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('RoomID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('done', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['RoomID'], ['room.RoomID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('permissions', sa.TEXT(), nullable=True),
    sa.Column('update_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room',
    sa.Column('RoomID', sa.VARCHAR(length=36), nullable=False),
    sa.Column('HostUserID', sa.INTEGER(), nullable=False),
    sa.Column('RoomCreated', sa.DATETIME(), nullable=True),
    sa.Column('RoomStatus', sa.VARCHAR(length=50), nullable=True),
    sa.Column('Location', sa.VARCHAR(length=150), nullable=True),
    sa.Column('WinningRestaurant', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['HostUserID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['WinningRestaurant'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('RoomID')
    )
    # ### end Alembic commands ###
