"""initial schema

Revision ID: 9fe5c3792dcb
Revises: 
Create Date: 2025-09-17 22:48:40.756940

"""
from alembic import op
import sqlalchemy as sa
from flask_security.datastore import AsaList


# revision identifiers, used by Alembic.
revision = '9fe5c3792dcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', AsaList(), nullable=True),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('fs_webauthn_user_handle', sa.String(length=64), nullable=True),
    sa.Column('mf_recovery_codes', AsaList(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('us_phone_number', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('us_totp_secrets', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('current_login_ip', sa.String(length=64), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('tf_primary_method', sa.String(length=64), nullable=True),
    sa.Column('tf_totp_secret', sa.String(length=255), nullable=True),
    sa.Column('tf_phone_number', sa.String(length=128), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier'),
    sa.UniqueConstraint('fs_webauthn_user_handle'),
    sa.UniqueConstraint('us_phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('room',
    sa.Column('RoomID', sa.String(length=36), nullable=False),
    sa.Column('HostUserID', sa.Integer(), nullable=False),
    sa.Column('RoomCreated', sa.DateTime(), nullable=True),
    sa.Column('RoomStatus', sa.String(length=50), nullable=True),
    sa.Column('Location', sa.String(length=150), nullable=True),
    sa.Column('WinningRestaurant', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['HostUserID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['WinningRestaurant'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('RoomID')
    )
    op.create_table('guest_user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('Username', sa.String(length=150), nullable=False),
    sa.Column('RoomID', sa.String(length=36), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['RoomID'], ['room.RoomID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_restaurants',
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('restaurant_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.RoomID'], ),
    sa.PrimaryKeyConstraint('room_id', 'restaurant_id')
    )
    op.create_table('vote',
    sa.Column('VoteID', sa.String(length=36), nullable=False),
    sa.Column('GuestUserID', sa.String(length=36), nullable=False),
    sa.Column('RoomID', sa.String(length=36), nullable=False),
    sa.Column('RestaurantID', sa.String(length=255), nullable=False),
    sa.Column('VoteChoice', sa.Integer(), nullable=False),
    sa.Column('VoteTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['GuestUserID'], ['guest_user.id'], ),
    sa.ForeignKeyConstraint(['RestaurantID'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['RoomID'], ['room.RoomID'], ),
    sa.PrimaryKeyConstraint('VoteID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('room_restaurants')
    op.drop_table('guest_user')
    op.drop_table('room')
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
